version: '3'

services:
  db:
    image: postgres
    # postgres_dataはDockerが内部で管理するもの（ローカルに作成されない）
    # コンテナを削除して作り直してもDBのデータは保存されたままにする
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: # docker-compose.ymlがあるフォルダから見てビルド
      context: ..
      dockerfile: ./docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/app # docker-compose.ymlがあるフォルダをWORKDIRにマウント
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=report_project.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

volumes:
  postgres_data: